### ISSUE TITLE
Restart repo due to bloat

### ISSUE THREAD

**Issue by daved** [champagneabuelo/openboard#6]
The repo history includes a build artifact from the first commit. I suggest that the repo be restarted to avoid megs of bloat. If the artifact had been committed in isolation, we might be able to cherry-pick our way to a clean history, but I don't think a clean solution is available.

**Comment by champagneabuelo** [comment]
Ah yeah, definitely agree. What would be the best way to restart the repo?

**Comment by daved** [comment]
I'm working on an orphaned branch at the moment which, if satisfactory, can be forced to master (I think). I'm not sure how it would affect issues/prs on github, but this is early enough that the grief should be minimal.

**Comment by champagneabuelo** [comment]
Great. I think if that's the case, #4 might be the only thing that will get affected. Thanks for catching this!

**Comment by nqthqn** [comment]
fine by me!

**Comment by daved** [comment]
Here's what I have currently (https://github.com/daved/openboard/tree/new/trial-a). The grpc and http servers can be wired up fairly quickly.

If this is OK, then it will need to be forced to master so that the binary files in the old history can be GCed at some point.

**Comment by champagneabuelo** [comment]
This looks good to me, go ahead and force it into master whenever you're ready! 
Should I delete the repo on my local machine before pulling the new version?

**Comment by daved** [comment]
It seems that my account does not have permission to push to master.

I think these directions will help us get our upstreams back in shape: https://stackoverflow.com/a/9813888

**Comment by daved** [comment]
OK, this is all done. I found that the normal `git gc` commands didn't seem to help reduce the existing object directory, so I had to re-clone the project to be sure that the project no longer contained the binary files. All seems well now.
