### ISSUE TITLE
Wire up grpc server with empty service implementations

### ISSUE THREAD

**Issue by daved** [champagneabuelo/openboard#8]
The following interfaces need to be implemented and wired up for the grpc server:
https://github.com/champagneabuelo/openboard/blob/a68d9ac95d18d5d53883dc404dbbe40797a22f4f/back/pb/auth.pb.go#L338-L343
https://github.com/champagneabuelo/openboard/blob/a68d9ac95d18d5d53883dc404dbbe40797a22f4f/back/pb/user.pb.go#L860-L868

The current messages and methods are just for getting things started and we can/should discuss the design soon.

**Comment by nqthqn** [comment]
What is a `Voucher`?

**Comment by daved** [comment]
Requesting a voucher will result in an email being sent out with a token that can be used within a certain window of time in order to do things like confirm an email address or update a password. This allows the auth portion of the code to focus on authentication and the user portion of the code to focus on user data. They then "interact" in the authorization layer (likely to be called "user access control(ler)".

For example:

1. Request new User
2. Receive valid User response with "hold" placed on sensitive field values
3. Request Voucher using an email field
4. Receive valid Voucher response (indicating the caller should check the provided email address inbox)
5. Check for Token by email
6. Request update to User with hold removed (limited by email address in Token) before expiration
7. Receive valid User response with field values set correctly

I suspect that we'll be able to add an "input token" and "token" field to the Voucher request/response messages to enable programmatic third-party authentication (e.g. github, google). This would allow the user to do something like:

1. Request Voucher using a "third-party token" field
2. Receive valid Voucher response (with Token)
3. Request new User without hold set (limited by email address in Token) before expiration
4. Receive valid User response with field values set correctly
